services:
  nginx-devlocal:
    container_name: "fizzbuzz-nginx"
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - php-devlocal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - "$PWD/..:/var/fizzbuzz"
    ports:
      - "127.0.0.1:33080:80"
    networks:
      - fizzbuzz-networks

  php-devlocal:
    container_name: "fizzbuzz-php"
    build:
      context: ../.
      dockerfile: docker/php/Dockerfile
      tags:
        - php-fizzbuzz
    user: 1000:1000
    volumes:
      - ../../log:/var/fizzbuzz/log
      - "$PWD/..:/var/fizzbuzz"
      - "$PWD/..:$PWD/.."
    working_dir: $PWD/..
    depends_on:
      mariadb:
        condition: service_started
    networks:
      - fizzbuzz-networks
  
  mariadb:
    image: mariadb:10
    container_name: "fizzbuzz-mariadb"
    restart: always
    volumes: 
      - fizzbuzz-db:/var/lib/mysql
      - ../../mariabackup:/backup
    env_file:
      - ./mariadb/db.env
    networks:
      - fizzbuzz-networks

networks:
  fizzbuzz-networks: 
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:1:1::/112
          gateway: fd00:1:1::1

volumes:
  fizzbuzz-db:
